package controllers;
import java.util.HashMap;

public class RiddleController {
    public static HashMap<Integer, RiddleData> adivinanzas = new HashMap<>();

    public static void crearAdivinanzas()
    {
        adivinanzas.put(0, new RiddleData("Van dos y..", "Se cae el de la izquierda", "Se cae el de la derecha", "Se cae tu puta madre", "Se cae tu puta madre"));
        adivinanzas.put(1, new RiddleData("Soy alto cuando soy joven, y bajo cuando soy viejo. ¿Quién soy?", "Una vela", "Una montaña", "Una persona", "Una vela"));
        adivinanzas.put(2, new RiddleData("Cuanto más seco, más mojado. ¿Qué es?", "Una esponja", "Una toalla", "Un paraguas", "Una toalla"));
        adivinanzas.put(3, new RiddleData("¿Qué tiene ciudades pero no casas, montañas pero no árboles, y mares pero no agua?", "Un globo terráqueo", "Un mapa", "Un atlas", "Un mapa"));
        adivinanzas.put(4, new RiddleData("Tengo agujas pero no sirvo para coser. ¿Qué soy?", "Un reloj", "Un cactus", "Una brújula", "Un reloj"));
        adivinanzas.put(5, new RiddleData("¿Qué tiene un ojo pero no puede ver?", "Una aguja", "Una cerradura", "Un espejo", "Una aguja"));
        adivinanzas.put(6, new RiddleData("Si me nombras, desaparezco. ¿Qué soy?", "El silencio", "La sombra", "El aire", "El silencio"));
        adivinanzas.put(7, new RiddleData("Vuelo sin alas, lloro sin ojos. ¿Qué soy?", "El viento", "Una nube", "Un tornado", "Una nube"));
        adivinanzas.put(8, new RiddleData("Tengo dientes pero no puedo morder. ¿Qué soy?", "Un peine", "Un serrucho", "Una llave", "Un peine"));
        adivinanzas.put(9, new RiddleData("Camina sin pies, vuela sin alas, silba sin boca. ¿Qué es?", "El viento", "La sombra", "El río", "El viento"));
        adivinanzas.put(10, new RiddleData("Si te caes en mí, me mojarás. ¿Quién soy?", "Un río", "El agua", "La lluvia", "El agua"));
        adivinanzas.put(11, new RiddleData("Tengo manos pero no puedo aplaudir. ¿Qué soy?", "Un reloj", "Un muñeco", "Un árbol", "Un reloj"));
        adivinanzas.put(12, new RiddleData("Entre más quitas, más grande me hago. ¿Qué soy?", "Un hoyo", "Una sombra", "El aire", "Un hoyo"));
        adivinanzas.put(13, new RiddleData("Tengo cuello pero no cabeza. ¿Qué soy?", "Una botella", "Un jarrón", "Un cisne", "Una botella"));
        adivinanzas.put(14, new RiddleData("Vuelo todo el día, pero no salgo del sitio. ¿Qué soy?", "Una veleta", "Un colibrí", "Un mosquito", "Una veleta"));
        adivinanzas.put(15, new RiddleData("Siempre estoy en el medio del mar. ¿Qué soy?", "La letra A", "La letra M", "La letra R", "La letra A"));
        adivinanzas.put(16, new RiddleData("Subo y bajo, pero nunca me muevo. ¿Qué soy?", "Un termómetro", "Un ascensor", "Una montaña rusa", "Un termómetro"));
        adivinanzas.put(17, new RiddleData("Mientras más hay de mí, menos ves. ¿Qué soy?", "La oscuridad", "La niebla", "El humo", "La oscuridad"));
        adivinanzas.put(18, new RiddleData("Tiene llaves pero no cerraduras. ¿Qué soy?", "Un piano", "Una puerta", "Un candado", "Un piano"));
        adivinanzas.put(19, new RiddleData("Me puedes romper sin tocarme. ¿Qué soy?", "Una promesa", "Un vidrio", "Un silencio", "Una promesa"));
        adivinanzas.put(20, new RiddleData("Todos me pueden abrir, pero nadie me puede cerrar. ¿Qué soy?", "Un huevo", "Un libro", "Un sobre", "Un huevo"));
        adivinanzas.put(21, new RiddleData("Camina sobre mi espalda pero nunca deja huellas. ¿Qué soy?", "Un puente", "Una alfombra", "Un piso", "Un puente"));
        adivinanzas.put(22, new RiddleData("Vuelo sin motor, pero no soy pájaro. ¿Qué soy?", "Una cometa", "Un avión", "Una pluma", "Una cometa"));
        adivinanzas.put(23, new RiddleData("Llena la casa pero no ocupa espacio. ¿Qué soy?", "La luz", "El aire", "El humo", "La luz"));
        adivinanzas.put(24, new RiddleData("No tiene vida, pero crece. ¿Qué es?", "El fuego", "Un cristal", "Una sombra", "El fuego"));
        adivinanzas.put(25, new RiddleData("Tiene cuernos pero no es animal. ¿Qué es?", "Una luna", "Un caracol", "Un dilema", "Una luna"));
        adivinanzas.put(26, new RiddleData("Cuanto más quitas, más dejo atrás. ¿Qué soy?", "Las huellas", "Un camino", "Un túnel", "Las huellas"));
        adivinanzas.put(27, new RiddleData("Cuando me nombras, dejo de existir. ¿Qué soy?", "El silencio", "Un secreto", "Una sombra", "El silencio"));
        adivinanzas.put(28, new RiddleData("Tiene patas pero no camina. ¿Qué es?", "Una mesa", "Una cama", "Un banco", "Una mesa"));
        adivinanzas.put(29, new RiddleData("Tiene orejas pero no escucha. ¿Qué es?", "Una taza", "Una silla", "Un jarrón", "Una taza"));
        adivinanzas.put(30, new RiddleData("No puedo hablar, pero siempre respondo. ¿Qué soy?", "Un eco", "Un espejo", "Un robot", "Un eco"));
        adivinanzas.put(31, new RiddleData("Tengo una cola pero no soy animal. ¿Qué soy?", "Una cometa", "Un globo", "Una moneda", "Una cometa"));
        adivinanzas.put(32, new RiddleData("Tengo una cara pero no ojos. ¿Qué soy?", "Un reloj", "Una moneda", "Un dado", "Una moneda"));
        adivinanzas.put(33, new RiddleData("Siempre corro pero nunca me muevo. ¿Qué soy?", "Un río", "Un reloj", "Un carril", "Un río"));
        adivinanzas.put(34, new RiddleData("Soy más ligera que el aire, pero no puedes atraparme. ¿Qué soy?", "Una burbuja", "El humo", "El pensamiento", "Una burbuja"));
        adivinanzas.put(35, new RiddleData("Es tuyo pero lo usan más los demás. ¿Qué es?", "Tu nombre", "Tu tiempo", "Tu sombra", "Tu nombre"));
        adivinanzas.put(36, new RiddleData("Tengo orejas pero no escucho y duermo con zapatos. ¿Qué soy?", "Una cama", "Un zapato", "Una alfombra", "Una cama"));
        adivinanzas.put(37, new RiddleData("No tiene alas pero vuela. ¿Qué es?", "El tiempo", "El pensamiento", "El viento", "El tiempo"));
        adivinanzas.put(38, new RiddleData("Va subiendo, va bajando y no se mueve. ¿Qué es?", "Una escalera", "Un ascensor", "Una cuerda", "Una escalera"));
        adivinanzas.put(39, new RiddleData("Es más grande que un elefante, pero no pesa nada. ¿Qué es?", "Su sombra", "El aire", "Un pensamiento", "Su sombra"));
        adivinanzas.put(40, new RiddleData("Tiene ojos pero no ve, y una cola que mueve. ¿Qué es?", "Una aguja", "Un pez", "Una cometa", "Una aguja"));
        adivinanzas.put(41, new RiddleData("No se come pero sabe muy bien. ¿Qué es?", "Una broma", "El azúcar", "La miel", "Una broma"));
        adivinanzas.put(42, new RiddleData("Siempre va pero nunca llega. ¿Qué es?", "El mañana", "El horizonte", "El futuro", "El mañana"));
        adivinanzas.put(43, new RiddleData("Es redondo pero no rueda. ¿Qué es?", "Un plato", "Un reloj", "Una moneda", "Un plato"));
        adivinanzas.put(44, new RiddleData("Tiene una cola pero no es animal. ¿Qué es?", "Una moneda", "Un cometa", "Una cuerda", "Una moneda"));
        adivinanzas.put(45, new RiddleData("Se estira pero nunca se rompe. ¿Qué es?", "El chicle", "La piel", "El tiempo", "El tiempo"));
        adivinanzas.put(46, new RiddleData("Siempre te sigue pero nunca te alcanza. ¿Qué es?", "Tu sombra", "Tu reflejo", "Un sueño", "Tu sombra"));
        adivinanzas.put(47, new RiddleData("No es un ser vivo, pero tiene raíces. ¿Qué es?", "Un árbol", "Una sombra", "Un diente", "Un diente"));
        adivinanzas.put(48, new RiddleData("Tiene cuartos pero no habitaciones. ¿Qué es?", "Una casa", "Una moneda", "Un reloj", "Un reloj"));
        adivinanzas.put(49, new RiddleData("Siempre está delante de ti pero nunca lo alcanzas. ¿Qué es?", "El futuro", "Tu reflejo", "Tu sombra", "El futuro"));
        adivinanzas.put(50, new RiddleData("Soy tuyo pero los demás me usan más. ¿Qué soy?", "Tu tiempo", "Tu nombre", "Tu sombra", "Tu nombre"));
        adivinanzas.put(51, new RiddleData("Si me rompes, no hago ruido. ¿Qué soy?", "El silencio", "El papel", "Una promesa", "El silencio"));
        adivinanzas.put(52, new RiddleData("No tengo piernas, pero puedo correr. ¿Qué soy?", "Un río", "Un reloj", "Un coche", "Un río"));
        adivinanzas.put(53, new RiddleData("Cuanto más lavo, más sucia me vuelvo. ¿Qué soy?", "El agua", "Una esponja", "La ropa", "El agua"));
        adivinanzas.put(54, new RiddleData("Soy un animal, pero no respiro ni me muevo. ¿Qué soy?", "Un peluche", "Un dibujo", "Una estatua", "Una estatua"));
        adivinanzas.put(55, new RiddleData("Cuanto más me quitas, más grande me hago. ¿Qué soy?", "Un hoyo", "Un secreto", "Un río", "Un hoyo"));
        adivinanzas.put(56, new RiddleData("Si me tienes, quieres compartirlo. Si lo compartes, ya no lo tienes. ¿Qué soy?", "Un secreto", "Un deseo", "Un tesoro", "Un secreto"));
        adivinanzas.put(57, new RiddleData("Cuanto más me llenas, más ligero me vuelvo. ¿Qué soy?", "Un globo", "Una burbuja", "Un neumático", "Un globo"));
        adivinanzas.put(58, new RiddleData("Siempre estoy en movimiento, pero nunca avanzo. ¿Qué soy?", "Un reloj", "El tiempo", "Una rueda", "Un reloj"));
        adivinanzas.put(59, new RiddleData("Siempre estoy contigo pero no puedes verme. ¿Qué soy?", "El aire", "Tu sombra", "Tu conciencia", "El aire"));
        adivinanzas.put(60, new RiddleData("No soy vivo, pero crezco. No tengo pulmones, pero respiro. ¿Qué soy?", "El fuego", "Un cristal", "Un volcán", "El fuego"));
        adivinanzas.put(61, new RiddleData("Soy invisible, pero puedo ser fuerte. ¿Qué soy?", "El viento", "El amor", "El tiempo", "El viento"));
        adivinanzas.put(62, new RiddleData("Tengo ramas, pero no hojas. ¿Qué soy?", "Un árbol genealógico", "Una biblioteca", "Un mapa", "Un árbol genealógico"));
        adivinanzas.put(63, new RiddleData("Crecen en el suelo, pero se elevan al cielo. ¿Qué son?", "Los árboles", "Las montañas", "Las nubes", "Los árboles"));
        adivinanzas.put(64, new RiddleData("Tiene forma pero no cuerpo. ¿Qué soy?", "Una sombra", "Un reflejo", "El aire", "Una sombra"));
        adivinanzas.put(65, new RiddleData("Entre más me quitas, más dejo atrás. ¿Qué soy?", "Huellas", "Un camino", "El polvo", "Huellas"));
        adivinanzas.put(66, new RiddleData("No tengo ojos, pero puedo llorar. ¿Qué soy?", "Una nube", "Una vela", "El viento", "Una nube"));
        adivinanzas.put(67, new RiddleData("Tengo piel, pero no pelo. ¿Qué soy?", "Una fruta", "Un libro", "Una piedra", "Una fruta"));
        adivinanzas.put(68, new RiddleData("Cuando estoy vacío, peso más. ¿Qué soy?", "Un saco", "Un globo", "Un vaso", "Un saco"));
        adivinanzas.put(69, new RiddleData("Siempre subo, pero nunca bajo. ¿Qué soy?", "La edad", "El humo", "La temperatura", "La edad"));
        adivinanzas.put(70, new RiddleData("Puedo contener agua, pero no soy sólido. ¿Qué soy?", "Una nube", "Un charco", "Una esponja", "Una nube"));
        adivinanzas.put(71, new RiddleData("No tengo alas, pero puedo volar. ¿Qué soy?", "El tiempo", "El pensamiento", "El viento", "El tiempo"));
        adivinanzas.put(72, new RiddleData("Siempre caigo, pero nunca me levanto. ¿Qué soy?", "La lluvia", "La noche", "Una hoja", "La lluvia"));
        adivinanzas.put(73, new RiddleData("Cuando llego, desaparezco. ¿Qué soy?", "El día", "La noche", "El silencio", "El día"));
        adivinanzas.put(74, new RiddleData("No tengo huesos, pero puedo romperte. ¿Qué soy?", "El miedo", "El agua", "Una promesa", "El miedo"));
        adivinanzas.put(75, new RiddleData("Siempre corro, pero no tengo pies. ¿Qué soy?", "El tiempo", "Un río", "Una rueda", "El tiempo"));
        adivinanzas.put(76, new RiddleData("Me mojas cuando me usas. ¿Qué soy?", "Una toalla", "Una esponja", "Un paraguas", "Una toalla"));
        adivinanzas.put(77, new RiddleData("Cuanto más oscuro, más brillo. ¿Qué soy?", "Las estrellas", "El fuego", "La luna", "Las estrellas"));
        adivinanzas.put(78, new RiddleData("Tengo llaves, pero no puertas. ¿Qué soy?", "Un piano", "Un candado", "Una cerradura", "Un piano"));
        adivinanzas.put(79, new RiddleData("Estoy lleno de agujeros, pero aún contengo agua. ¿Qué soy?", "Una esponja", "Una red", "Un colador", "Una esponja"));
        adivinanzas.put(80, new RiddleData("Vuelo sin alas y caigo sin hacer ruido. ¿Qué soy?", "Un pensamiento", "El sueño", "El tiempo", "El pensamiento"));
        adivinanzas.put(81, new RiddleData("Siempre estoy detrás de ti, pero no puedo verte. ¿Qué soy?", "Tu sombra", "Tu pasado", "Tu reflejo", "Tu sombra"));
        adivinanzas.put(82, new RiddleData("Cuanto más me miras, menos me ves. ¿Qué soy?", "La oscuridad", "La luz", "El sol", "La oscuridad"));
        adivinanzas.put(83, new RiddleData("Tengo una corona, pero no reino. ¿Qué soy?", "Un diente", "Un rey", "Un árbol", "Un diente"));
        adivinanzas.put(84, new RiddleData("Soy invisible, pero a veces dejo huellas. ¿Qué soy?", "El viento", "Un fantasma", "El aire", "El viento"));
        adivinanzas.put(85, new RiddleData("Cuanto más me uso, más pequeño me hago. ¿Qué soy?", "Un lápiz", "Una vela", "Un borrador", "Una vela"));
        adivinanzas.put(86, new RiddleData("Siempre sube, pero nunca baja. ¿Qué es?", "El humo", "La temperatura", "La edad", "El humo"));
        adivinanzas.put(87, new RiddleData("Aunque no tengo manos, puedo aplaudir. ¿Qué soy?", "El trueno", "El viento", "El mar", "El trueno"));
        adivinanzas.put(88, new RiddleData("Mientras más me lavo, más sucia me vuelvo. ¿Qué soy?", "El agua", "El jabón", "Una esponja", "El agua"));
        adivinanzas.put(89, new RiddleData("Me puedes ver, pero no tocar. ¿Qué soy?", "Un arcoíris", "El horizonte", "El reflejo", "Un arcoíris"));
        adivinanzas.put(90, new RiddleData("Siempre te sigo, pero no me puedes atrapar. ¿Qué soy?", "Tu sombra", "El tiempo", "El pasado", "Tu sombra"));
        adivinanzas.put(91, new RiddleData("Soy pequeño, pero puedo llenar una habitación. ¿Qué soy?", "Una vela", "El aire", "La luz", "La luz"));
        adivinanzas.put(92, new RiddleData("Nadie me puede ver, pero todos saben que existo. ¿Qué soy?", "El viento", "El tiempo", "El silencio", "El tiempo"));
        adivinanzas.put(93, new RiddleData("Mientras más grande soy, menos puedo verte. ¿Qué soy?", "La oscuridad", "La niebla", "El humo", "La oscuridad"));
        adivinanzas.put(94, new RiddleData("Mientras más me llenas, más vacío estoy. ¿Qué soy?", "Un vaso", "Un agujero", "Un saco", "Un agujero"));
        adivinanzas.put(95, new RiddleData("Mientras más me miras, más me alejo. ¿Qué soy?", "El horizonte", "Un sueño", "El pasado", "El horizonte"));
        adivinanzas.put(96, new RiddleData("Vuelo todo el día, pero no salgo del lugar. ¿Qué soy?", "Una veleta", "Un helicóptero", "Una bandera", "Una veleta"));
        adivinanzas.put(97, new RiddleData("No soy vivo, pero tengo raíces. ¿Qué soy?", "Un árbol", "Un diente", "Un edificio", "Un diente"));
        adivinanzas.put(98, new RiddleData("Siempre te sigo y copio, pero nunca me alcanzas. ¿Qué soy?", "Tu sombra", "Tu reflejo", "Un eco", "Tu sombra"));
        adivinanzas.put(99, new RiddleData("Soy suave y cálido, pero puedo hacer daño. ¿Qué soy?", "El fuego", "El sol", "El amor", "El fuego"));
        adivinanzas.put(100, new RiddleData("Estoy hecho para caminar, pero no tengo pies. ¿Qué soy?", "Un zapato", "Un camino", "Un puente", "Un zapato"));
        adivinanzas.put(101, new RiddleData("Soy el inicial tipo planta, tengo una semilla en mi espalda. ¿Quién soy?", "Bulbasaur", "Oddish", "Exeggcute", "Bulbasaur"));
        adivinanzas.put(102, new RiddleData("Evoluciono con una piedra trueno y tengo rayos. ¿Quién soy?", "Jolteon", "Raichu", "Pikachu", "Raichu"));
        adivinanzas.put(103, new RiddleData("Soy un ave legendaria con plumas de fuego. ¿Quién soy?", "Moltres", "Charizard", "Pidgeot", "Moltres"));
        adivinanzas.put(104, new RiddleData("Tengo un caparazón y giro rápidamente en el agua. ¿Quién soy?", "Blastoise", "Cloyster", "Squirtle", "Blastoise"));
        adivinanzas.put(105, new RiddleData("Soy rosado, pequeño y puedo transformarme en cualquier cosa. ¿Quién soy?", "Ditto", "Clefairy", "Jigglypuff", "Ditto"));
        adivinanzas.put(106, new RiddleData("Tengo tres cabezas y vivo en el suelo. ¿Quién soy?", "Dodrio", "Dugtrio", "Exeggutor", "Dugtrio"));
        adivinanzas.put(107, new RiddleData("Soy un dragón azul y mi preevolución es Dratini. ¿Quién soy?", "Dragonite", "Dragonair", "Gyarados", "Dragonair"));
        adivinanzas.put(108, new RiddleData("Tengo cuernos y corro velozmente en estampidas. ¿Quién soy?", "Tauros", "Rapidash", "Rhydon", "Tauros"));
        adivinanzas.put(109, new RiddleData("Tengo la habilidad de dormir a otros con mi canción. ¿Quién soy?", "Jigglypuff", "Clefairy", "Hypno", "Jigglypuff"));
        adivinanzas.put(110, new RiddleData("Soy el inicial tipo fuego y evoluciono a Charizard. ¿Quién soy?", "Charmander", "Magmar", "Flareon", "Charmander"));
        adivinanzas.put(111, new RiddleData("Soy un insecto verde y uso mi guadaña para cortar. ¿Quién soy?", "Scyther", "Pinsir", "Beedrill", "Scyther"));
        adivinanzas.put(112, new RiddleData("Soy azul y evoluciono en Vaporeon. ¿Quién soy?", "Eevee", "Poliwag", "Seel", "Eevee"));
        adivinanzas.put(113, new RiddleData("Tengo dos cabezas, pero en el futuro tendré tres. ¿Quién soy?", "Doduo", "Dugtrio", "Exeggcute", "Doduo"));
        adivinanzas.put(114, new RiddleData("Tengo un cráneo en la cabeza y busco a mi madre. ¿Quién soy?", "Cubone", "Marowak", "Rhyhorn", "Cubone"));
        adivinanzas.put(115, new RiddleData("Soy una estrella de mar que brilla intensamente. ¿Quién soy?", "Starmie", "Staryu", "Cloyster", "Starmie"));
        adivinanzas.put(116, new RiddleData("Soy un Pokémon psíquico con un cuchara. ¿Quién soy?", "Alakazam", "Kadabra", "Hypno", "Kadabra"));
        adivinanzas.put(117, new RiddleData("Tengo alas grandes y soy el ave legendaria del hielo. ¿Quién soy?", "Articuno", "Moltres", "Zapdos", "Articuno"));
        adivinanzas.put(118, new RiddleData("Soy eléctrico y tengo una forma de esfera. ¿Quién soy?", "Voltorb", "Electrode", "Magnemite", "Voltorb"));
        adivinanzas.put(119, new RiddleData("Soy un pez con un cuerno en la cabeza. ¿Quién soy?", "Seaking", "Goldeen", "Magikarp", "Goldeen"));
        adivinanzas.put(120, new RiddleData("Soy rosado y tengo un huevo en el vientre. ¿Quién soy?", "Chansey", "Clefairy", "Jigglypuff", "Chansey"));
        adivinanzas.put(121, new RiddleData("Soy amarillo, psíquico y tengo una gran cola. ¿Quién soy?", "Abra", "Kadabra", "Mewtwo", "Abra"));
        adivinanzas.put(122, new RiddleData("Soy un Pokémon fósil y mi nombre significa extinto. ¿Quién soy?", "Omanyte", "Aerodactyl", "Kabuto", "Aerodactyl"));
        adivinanzas.put(123, new RiddleData("Vivo bajo el agua y evoluciono a Gyarados. ¿Quién soy?", "Magikarp", "Goldeen", "Seaking", "Magikarp"));
        adivinanzas.put(124, new RiddleData("Soy una planta venenosa que evoluciona a Victreebel. ¿Quién soy?", "Weepinbell", "Bellsprout", "Oddish", "Weepinbell"));
        adivinanzas.put(125, new RiddleData("Soy un Pokémon de tipo fuego con una melena brillante. ¿Quién soy?", "Rapidash", "Arcanine", "Ponyta", "Rapidash"));
        adivinanzas.put(126, new RiddleData("Soy una roca en forma de serpiente. ¿Quién soy?", "Onix", "Geodude", "Graveler", "Onix"));
        adivinanzas.put(127, new RiddleData("Tengo poderes magnéticos y soy de tipo eléctrico. ¿Quién soy?", "Magnemite", "Electrode", "Voltorb", "Magnemite"));
        adivinanzas.put(128, new RiddleData("Soy un ave rápida con plumas brillantes. ¿Quién soy?", "Pidgeot", "Fearow", "Dodrio", "Pidgeot"));
        adivinanzas.put(129, new RiddleData("Soy amarillo y tengo un bigote largo. ¿Quién soy?", "Abra", "Hypno", "Drowzee", "Hypno"));
        adivinanzas.put(130, new RiddleData("Soy venenoso y tengo forma de arbusto con flores. ¿Quién soy?", "Gloom", "Vileplume", "Weepinbell", "Vileplume"));
        adivinanzas.put(131, new RiddleData("Soy un Pokémon helado con una concha en la espalda. ¿Quién soy?", "Cloyster", "Lapras", "Dewgong", "Lapras"));
        adivinanzas.put(132, new RiddleData("Soy un Pokémon psíquico con poderes genéticos. ¿Quién soy?", "Mew", "Alakazam", "Mewtwo", "Mewtwo"));
        adivinanzas.put(133, new RiddleData("Soy un Pokémon luchador con guantes de boxeo. ¿Quién soy?", "Hitmonchan", "Machamp", "Hitmonlee", "Hitmonchan"));
        adivinanzas.put(134, new RiddleData("Soy un Pokémon de fuego con alas y cuernos. ¿Quién soy?", "Charizard", "Dragonite", "Moltres", "Charizard"));
        adivinanzas.put(135, new RiddleData("Soy pequeño, amarillo y evoluciono con felicidad. ¿Quién soy?", "Pikachu", "Clefairy", "Togepi", "Pikachu"));
        adivinanzas.put(136, new RiddleData("Soy venenoso y tengo un caparazón espinoso. ¿Quién soy?", "Cloyster", "Tentacruel", "Nidoking", "Cloyster"));
        adivinanzas.put(137, new RiddleData("Soy una criatura marina con tentáculos largos. ¿Quién soy?", "Tentacruel", "Tentacool", "Gyarados", "Tentacruel"));
        adivinanzas.put(138, new RiddleData("Soy un fósil con forma de almeja. ¿Quién soy?", "Omanyte", "Kabuto", "Shellder", "Omanyte"));
        adivinanzas.put(139, new RiddleData("Soy azul y tengo una lengua larga. ¿Quién soy?", "Lickitung", "Poliwag", "Slowbro", "Lickitung"));
        adivinanzas.put(140, new RiddleData("Soy un Pokémon de tipo normal y evoluciono en tres formas. ¿Quién soy?", "Eevee", "Meowth", "Jigglypuff", "Eevee"));
        adivinanzas.put(141, new RiddleData("Soy un Pokémon de roca con un taladro en la cabeza. ¿Quién soy?", "Rhydon", "Golem", "Graveler", "Rhydon"));
        adivinanzas.put(142, new RiddleData("Soy un Pokémon azul con poderes psíquicos. ¿Quién soy?", "Slowbro", "Kadabra", "Starmie", "Slowbro"));
        adivinanzas.put(143, new RiddleData("Soy enorme, dormilón y muy difícil de mover. ¿Quién soy?", "Snorlax", "Lapras", "Chansey", "Snorlax"));
        adivinanzas.put(144, new RiddleData("Soy el ave legendaria del trueno. ¿Quién soy?", "Zapdos", "Articuno", "Fearow", "Zapdos"));
        adivinanzas.put(145, new RiddleData("Tengo una flama en la cola y evoluciono a Charmeleon. ¿Quién soy?", "Charmander", "Vulpix", "Ponyta", "Charmander"));
        adivinanzas.put(146, new RiddleData("Soy amarillo, pequeño y corro rápido. ¿Quién soy?", "Sandshrew", "Pikachu", "Rattata", "Sandshrew"));
        adivinanzas.put(147, new RiddleData("Soy un ave pequeño, y mi nombre es el mismo que mi sonido. ¿Quién soy?", "Pidgey", "Spearow", "Doduo", "Pidgey"));
        adivinanzas.put(148, new RiddleData("Tengo forma de huevo y soy un grupo de semillas. ¿Quién soy?", "Exeggcute", "Voltorb", "Electrode", "Exeggcute"));
        adivinanzas.put(149, new RiddleData("Soy el primer Pokémon que aparece en la Pokédex. ¿Quién soy?", "Bulbasaur", "Charmander", "Squirtle", "Bulbasaur"));
        adivinanzas.put(150, new RiddleData("Soy un Pokémon psíquico con poderes clonados. ¿Quién soy?", "Mewtwo", "Abra", "Alakazam", "Mewtwo"));
        adivinanzas.put(151, new RiddleData("Puto el que...", "Lo escriba", "Lo lea", "Lo oiga", "Lo lea"));
        adivinanzas.put(152, new RiddleData("Das marcha tras con el coche y...", "Te estrellas con el coche de atrás", "Te das con el pilar de al lado", "Te quedas quieto", "Te quedas quieto"));
        adivinanzas.put(153, new RiddleData("Carmen te obliga a ir en su coche, que le respondes?", "No, sin justificar la respuesta", "Si, con el peligro que ello conlleva", "No, porque donde esté ya no tendrá coche", "Si, con el peligro que ello conlleva"));
        adivinanzas.put(154, new RiddleData("Cual es la respuesta? XD", "equisde", "XD", "cual", "cual"));
        adivinanzas.put(155, new RiddleData("¿Es aconsejable conducir un turismo calzado con unas chanclas?", "Sí, porque permiten un manejo más rápido y seguro de los pedales.", "No, porque podrían caerse y dificultar el manejo de los pedales.", "Sí, porque al no sujetar el pie, es más fácil ejercer la presión correcta sobre los pedales.", "No, porque podrían caerse y dificultar el manejo de los pedales."));
        adivinanzas.put(156, new RiddleData("Con los dedos de las manos, con los dedos de los pies ... ", "Con el tetrabrick en la mano suman 21", "con la polla y los cojones todo suma 23", "me la agarras otra vez", "con la polla y los cojones todo suma 23"));
        adivinanzas.put(157, new RiddleData("En el transporte de materias radiactivas, además de en las Instrucciones escritas, ¿dónde deberán incluirse las medidas a tomar en caso de emergencia?", "En el contrato de transporte.", "En la carta de porte.", "En una declaración suplementaria redactada por el expedidor.", "En una declaración suplementaria redactada por el expedidor."));

    }
}

// adivinanzas.put(N, new RiddleData("", "", "", "", ""));
